FROM golang:1.14 AS builder
WORKDIR /app
COPY go.mod /app
COPY go.sum /app
RUN go mod download
COPY gqlgen.yml /app
COPY server.go /app
COPY ./src /app/src

RUN CGO_ENABLED=0 go build -o main .

FROM alpine:3.11

RUN apk --no-cache add ca-certificates

WORKDIR /root

COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]